name: CI - Push

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:

  build-swiftpm:
    name: Build SwiftPM
    uses: ./.github/workflows/build-swiftpm.yml
    secrets: inherit
    
  bump:
    name: Bump version
    needs: build-swiftpm
    uses: ./.github/workflows/bump.yml
    secrets: inherit
    
