name: CI - Push

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:

  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    with:
      package: "OversizeNetwork"
    secrets: inherit
    
  bump:
    name: Bump version
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
    secrets: inherit
    
